language: cpp

matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_CXX=off
        - os: linux
          compiler: gcc
          env: BUILD_CXX=on
        - os: osx
          compiler: clang
          env: BUILD_CXX=off
        - os: osx
          compiler: clang
          env: BUILD_CXX=on

script:
    - set -e
    - ./bootstrap.sh
    - CFLAGS=-ffast-math ./configure --enable-simdoverride
    - make
    - make check
