language: cpp

matrix:
    include:
        - os: linux
          compiler: gcc
          env: BUILD_CXX=off
        - os: linux
          compiler: gcc
          env: BUILD_CXX=on
        - os: osx
          compiler: clang
          env: BUILD_CXX=off
        - os: osx
          compiler: clang
          env: BUILD_CXX=on

script:
    - set -e
    - mkdir -p "libcorrect"
    - git clone https://github.com/quiet/libcorrect.git
    - cd libcorrect
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release .. && make && make shim
    - sudo make install
    - cd ../..
    - ./bootstrap.sh
    - ./configure
    - make
    - make check
